//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test.proto

package net.kigawa.kmcmanager.proto;

@kotlin.jvm.JvmName("-initializegetUserResponse")
inline fun getUserResponse(block: net.kigawa.kmcmanager.proto.GetUserResponseKt.Dsl.() -> kotlin.Unit): net.kigawa.kmcmanager.proto.Test.GetUserResponse =
  net.kigawa.kmcmanager.proto.GetUserResponseKt.Dsl._create(net.kigawa.kmcmanager.proto.Test.GetUserResponse.newBuilder()).apply { block() }._build()
object GetUserResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: net.kigawa.kmcmanager.proto.Test.GetUserResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: net.kigawa.kmcmanager.proto.Test.GetUserResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): net.kigawa.kmcmanager.proto.Test.GetUserResponse = _builder.build()

    /**
     * <pre>
     * メール
     * </pre>
     *
     * <code>string mail = 1;</code>
     */
    var mail: kotlin.String
      @JvmName("getMail")
      get() = _builder.getMail()
      @JvmName("setMail")
      set(value) {
        _builder.setMail(value)
      }
    /**
     * <pre>
     * メール
     * </pre>
     *
     * <code>string mail = 1;</code>
     */
    fun clearMail() {
      _builder.clearMail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun net.kigawa.kmcmanager.proto.Test.GetUserResponse.copy(block: net.kigawa.kmcmanager.proto.GetUserResponseKt.Dsl.() -> kotlin.Unit): net.kigawa.kmcmanager.proto.Test.GetUserResponse =
  net.kigawa.kmcmanager.proto.GetUserResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

